general:
  buildTool: 'docker'
  gitHttpsCredentialsId: githubPersonalToken
  productiveBranch: 'kyma/app'
steps:
  buildExecute: 
    dockerImageName: cloud-cap-risk-management
  artifactPrepareVersion:
    dockerVersionSource: custom
    filePath: cfg/VERSION  
  
